apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      derivedFields:
        - name: Trace
          matcherRegex: '"trace_id"[:\s]*"([a-f0-9]+)"'
          url: "$${__value.raw}"
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'
        filterByTraceID: true
        tags:
          - key: 'service.name'
            value: 'service_name'