name = "bank"
hostname = ""
bootstrap = "localhost:30001,localhost:30002,localhost:30003"

[pc]
"enable.auto.commit" = "false"
"auto.offset.reset" = "earliest"
"isolation.level" = "read_committed"
"group.protocol" = "consumer"

[pp]
"linger.ms" = "1"
