name = "bank"
bootstrap = "localhost:30001,localhost:30002,localhost:30003"

[subscriber.Account]

[subscriber.Transaction]
hotspot = true

[cc.Account]
"auto.offset.reset" = "earliest"
"auto.commit.interval.ms" = "1000"
"group.protocol" = "consumer"

[cc.Transaction]
"auto.offset.reset" = "earliest"
"auto.commit.interval.ms" = "1000"
"group.protocol" = "consumer"

[tp]
"linger.ms" = "5"

[admin]
