[validation.zh]
"required" = "必填"
"min_length" = "最小长度为 {min}"
"max_length" = "最大长度为 {max}"
"range_length" = "长度应介于 {min} 到 {max} 之间"
"exact_length" = "长度应为 {equal}"
"min_num" = "最小值为 {min}"
"max_num" = "最大值为 {max}"
"range_num" = "值应介于 {min} 到 {max} 之间"
"ascii_digit" = "应为 ASCII 数字"
"set_limit" = "交易限额不得大于控制限额"

[validation.en]
"required" = "required"
"min_length" = "min lenth is {min}"
"max_length" = "max lenth is {max}"
"range_length" = "length should between {min} and {max}"
"exact_length" = "length should be {equal}"
"min_num" = "min number is {min}"
"max_num" = "max number is {max}"
"range_num" = "number should between {min} and {max}"
"ascii_digit" = "should be ASCII digit"
"set_limit" = "transaction limit should not great than limit"
