[validation.zh]
"required" = "必填"
"min_length" = "最小长度为 {min}"
"max_length" = "最大长度为 {max}"
"exact_length" = "长度应为 {equal}"
"ascii_digit" = "应为 ASCII 数字"

[validation.en]
"required" = "required"
"min_length" = "min lenth is {min}"
"max_length" = "max lenth is {max}"
"exact_length" = "length should be {equal}"
"ascii_digit" = "should be ASCII digit"
