name = "bank"
hostname = ""
bootstrap = "localhost:30001,localhost:30002,localhost:30003"

[subscriber.Account]
hotspot = true
sems = 300

[sender.Account]
sems = 50

[cc.Account]
"auto.offset.reset" = "earliest"
"auto.commit.interval.ms" = "1000"
"group.protocol" = "consumer"

[tc.Account]
"auto.offset.reset" = "earliest"
"auto.commit.interval.ms" = "1000"
"group.protocol" = "consumer"

[tp]
"linger.ms" = "1"

[cp]
"linger.ms" = "1"
