[response.zh]
"validate" = "命令数据验证错误"
"auth" = "身份验证错误"
"timeout" = "请求超时"
"conflict" = "被冲突的新命令取代"
"check" = "命令无法应用到聚合"
"code" = "序列化错误"
"msg" = "消息处理错误"
"write" = "写入事件流错误"
"read" = "读取事件流错误"
"send" = "写入命令流错误"

[response.en]
"validate" = "validate error"
"auth" = "auth error"
"timeout" = "request timeout"
"conflict" = "被冲突的新命令取代"
"check" = "check error"
"code" = "encode/decode error"
"msg" = "message error"
"write" = "write error"
"read" = "read error"
"send" = "send error"

[validation.zh]
"required" = "必填"
"min_length" = "最小长度为 {min}"
"max_length" = "最大长度为 {max}"
"exact_length" = "长度应为 {equal}"
"ascii_digit" = "应为 ASCII 数字"

[validation.en]
"required" = "required"
"min_length" = "min lenth is {min}"
"max_length" = "max lenth is {max}"
"exact_length" = "length should be {equal}"
"ascii_digit" = "should be ASCII digit"
